name: CI
on: 
  pull_request:  
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    #if: startsWith(github.event.head_commit.message, 'Finally Merge')
    runs-on: ubuntu-latest
    steps:
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v1
    - name: Run a one-line script 
      run: |
         echo Hello, world!
         echo "::error::My error message"
     
    - run: 
        echo hello

  
