name: Push 

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#       - uses: octokit/request-action@v2.x
#         id: get_PR_commits
#         with:
#           route: GET /repos/:repo/pulls/:pull_number/commits
#           repo: ${{ github.repository }}
#           pull_number: ${{ github.event.issue.number }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: set commit to output
#         id: getcommit
#         run: | 
#            prsha=$(echo $response | jq '.[-1].sha'  | tr -d '"')
#            echo "::set-output name=sha::$prsha" 
#         env: 
#           response:  ${{ steps.get_PR_commits.outputs.data }}
          
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{steps.getcommit.outputs.sha}}  

      
    - uses: actions/checkout@v2
      with:
        repository: zhuorg/prtest
#         token: ${{secrets.PAT_FOR_PUSH}}
    - name: Create local changes
      run: |
        cat > sales662.txt
   # git remote add private https://github.com/zhuorg/private_one.git  
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Add changes" -a
        git remote add origin2 https://github.com/zhuorg/private_one.git
        git push -u origin2 $GITHUB_REF 
      env:
        REPO_KEY: ${{secrets.PAT_FOR_PUSH}}
        USERNAME: github-actions
