name: Push 
on:  
  push: 
    tags:
    - feature.*

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2


    - name: Create local changes
      run: |
        cat > sales661.txt
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Add changes" -a
        git tag v5.1
        git push origin v5.1

     
    #- name: Push changes
    #  uses: Woile/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GPR_ACCESS_TOKEN }}
    #   tags: "true"
