name: testif
on: 
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [13.x] ii

    steps:
      - run: echo YAY
      - uses: actions/checkout@v1
      - id: action_with_json_output
        run: 'echo ::set-output name=data::{ "text": "*${{ github.workflow }}*\n`${{ job.status }}`" }'
      - run: 
          echo ${{ steps.action_with_json_output.outputs.data }}
#       - run: echo "::warning file=app.js,line=1,col=5::Missing semicolon"  
#       - name: get sha
#         run: |
#           SHA=${GITHUB_SHA:0:7}
#           echo $SHA
#           echo "[${SHA}](${{ github.event.compare }})"

