name: testif
on: 
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [13.x] ii

    steps:
      - run: echo YAY
#       - run: |
#           if [ "$MY_SECRET" != "true" ]; then
#             echo WOOHOO
#           fi
#         env:
#           MY_SECRET: ${{ secrets.SKIP_RELEASE }}
      - uses: actions/checkout@v1
      - name: get sha
        run: |
          
          echo $SHA
          echo "[`${SHA}`](${{ github.event.compare }})"
        env: 
          SHA: ${GITHUB_SHA:0:7}
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#           registry-url: https://npm.pkg.github.com/
#           scope: '@ownername'
#       - name: npm install build and test
#         run: |
#           npm install
#         env:
#           CI: true
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
