name: create zip 
on: 
  push: 
    paths: 
      - '.github/workflows/new2.yml'
jobs:
  job1-test:
    runs-on: macos-latest
    steps:
      - run: echo $HOSTNAME
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

