name: create zip 
on: 
  push: 
    paths: 
      - '.github/workflows/new2.yml'
jobs:
  job1-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $HOSTNAME
      - name: Dump runner context
        if: ${{ success() }}
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: | 
           echo "$RUNNER_CONTEXT"
           chmod 755 build/setenv.sh
           build/setenv.sh --display
           build/setenv.sh --display
        

