name: deployment
on:
  deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ tojson(github) }}
          ENVIRONMENT: ${{ github.event.deployment.environment }}
       run: |
          echo "$GITHUB_CONTEXT"
          echo $ENVIRONMENT
#      - uses: actions/checkout@v2
#      - name: Update release
#        uses: johnwbyrd/update-release@v1.0.0
#        with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           files: ./.github/workflows/prerelease.yml
#           release: '1.0.0'
